"""Configuracoes principais da Raspberry Pi."""

BAUD_RATE = 115200

# Use SERIAL_PORT = None para tentar detectar automaticamente.
# Se a deteccao falhar, definir manualmente, por exemplo:
# SERIAL_PORT = "/dev/ttyACM0"
SERIAL_PORT = None

VELOCIDADE_TESTE_BAIXA = 60
VELOCIDADE_TESTE_MEDIA = 80
VELOCIDADE_MAXIMA_SEGURA = 120
TIMEOUT_SERIAL = 2.0

MOTORES_ATIVADOS = True

CAMERA_HEIGHT_CM = 8
CAMERA_TILT_DEGREES = 35
CAMERA_FOV_DEGREES = 160

CAMERA_WIDTH = 640
CAMERA_HEIGHT = 480
CAMERA_FPS = 30
PASTA_CAPTURAS = "captures"

# ===============================
# CONFIGURACOES DA LINHA PRETA
# ===============================

# ROI em proporcao da imagem inteira.
ROI_Y_INICIO = 0.20
ROI_Y_FIM = 1.00
ROI_X_INICIO = 0.05
ROI_X_FIM = 0.95

# A parte superior esta mais distante da camera.
DIVISAO_TOPO_BAIXO = 0.40

# Preto em BGR: os tres canais da linha devem estar baixos.
PRETO_MIN_BGR = [0, 0, 0]
PRETO_MAX_TOPO_BGR = [90, 90, 90]
PRETO_MAX_BAIXO_BGR = [145, 145, 145]

# Area minima para aceitar um contorno como linha.
AREA_MINIMA_LINHA = 1500

# Limpeza simples da mascara.
KERNEL_LINHA = 3
ERODE_INICIAL = 2
DILATE_LINHA = 6
ERODE_FINAL = 2

# ===============================
# CONFIGURACOES DO COMANDO SUGERIDO
# ===============================

# Valores seguros para o primeiro teste real do robo.
# A ideia e comecar devagar e aumentar depois.
VELOCIDADE_BASE_SEGUE_LINHA = 60
VELOCIDADE_MINIMA_SEGUE_LINHA = 35
VELOCIDADE_MAXIMA_SEGUE_LINHA = 90

# Ganho proporcional inicial mais suave.
KP_SEGUE_LINHA = 0.30
CORRECAO_MAXIMA = 30

# Faixas proporcionais dentro da ROI.
FAIXA_BAIXA_INICIO = 0.65
FAIXA_BAIXA_FIM = 1.00
FAIXA_MEDIA_INICIO = 0.35
FAIXA_MEDIA_FIM = 0.65
FAIXA_ALTA_INICIO = 0.00
FAIXA_ALTA_FIM = 0.35

# A faixa baixa e a mais importante para a decisao.
PESO_FAIXA_BAIXA = 0.70
PESO_FAIXA_MEDIA = 0.25
PESO_FAIXA_ALTA = 0.05

# ===============================
# CONFIGURACOES DO PRIMEIRO SEGUE-LINHA REAL
# ===============================

DURACAO_TESTE_SEGUE_LINHA = 3.0
INTERVALO_COMANDO_SEGUNDOS = 0.10
PARAR_SE_PERDER_LINHA = True
MAX_FRAMES_SEM_LINHA = 2

# ===============================
# CONFIGURACOES DA SPEC 06
# RECUPERACAO DE LINHA E CURVA FECHADA
# ===============================

LIMIAR_ERRO_CURVA_FECHADA = 75
LIMIAR_ERRO_BAIXO_CURVA_FECHADA = 85
VELOCIDADE_BASE_NORMAL = 60
VELOCIDADE_BASE_CURVA_FECHADA = 50
KP_NORMAL = 0.30
KP_CURVA_FECHADA = 0.45
CORRECAO_MAXIMA_NORMAL = 30
CORRECAO_MAXIMA_CURVA_FECHADA = 45
VELOCIDADE_MAXIMA_CURVA_FECHADA = 95
VELOCIDADE_MINIMA_CURVA_FECHADA = 25
VELOCIDADE_GIRO_BUSCA = 50
TEMPO_MAX_BUSCA_LINHA = 1.2
MAX_FRAMES_SEM_LINHA_ANTES_BUSCA = 1
MAX_FRAMES_BUSCA_SEM_LINHA = 12
FRAMES_LINHA_REENCONTRADA = 2

# ===============================
# CONFIGURACOES DA SPEC 06.5
# CURVA 90 GRAUS COM PIVO CONTROLADO
# ===============================
LIMIAR_ERRO_CURVA_90 = 105
LIMIAR_ERRO_MEDIA_ALTA_CURVA_90 = 80
VELOCIDADE_GIRO_CURVA_90 = 55
TEMPO_MAX_CURVA_90 = 1.8
FRAMES_REENCONTRO_CURVA_90 = 2
LIMIAR_ERRO_SAIDA_CURVA_90 = 55
FRAMES_CONFIRMAR_CURVA_90 = 2
PAUSA_ANTES_GIRO_90 = 0.0

# ===============================
# SPEC 06.6 - CAMERA FRONTAL + ANTI-ZIGZAG
# ===============================
TEMPO_AVANCO_ANTES_GIRO_90 = 0.25
VELOCIDADE_AVANCO_ANTES_GIRO_90 = 45
TEMPO_MAX_GIRAR_90 = 2.0
TEMPO_MAX_TOTAL_CURVA_90 = 3.0
FRAMES_LINHA_BAIXA_REENCONTRADA_90 = 2
LIMIAR_ERRO_SAIDA_90 = 65
TEMPO_REALINHAR_POS_90 = 0.35
VELOCIDADE_BASE_REALINHAR_POS_90 = 45
KP_REALINHAR_POS_90 = 0.25
TAMANHO_HISTORICO_ERRO_ZIGZAG = 6
LIMIAR_ERRO_ZIGZAG = 35
MIN_TROCAS_SINAL_ZIGZAG = 2
TEMPO_MIN_ZIGZAG_SUAVE = 0.6
TEMPO_BLOQUEIO_CURVA_90_APOS_ZIGZAG = 1.0
VELOCIDADE_BASE_ZIGZAG = 50
KP_ZIGZAG = 0.18
CORRECAO_MAXIMA_ZIGZAG = 18
PESO_ZIGZAG_BAIXA = 0.85
PESO_ZIGZAG_MEDIA = 0.15
PESO_ZIGZAG_ALTA = 0.00

# ===============================
# SPEC 07 - VETOR E LOOKAHEAD
# ===============================
NUM_FAIXAS_CAMINHO = 9
Y_CONTROLE_PERTO_INICIO = 0.68
Y_CONTROLE_PERTO_FIM = 0.95
Y_LOOKAHEAD_INICIO = 0.35
Y_LOOKAHEAD_FIM = 0.68
Y_FUTURO_INICIO = 0.05
Y_FUTURO_FIM = 0.35
MIN_PIXELS_FAIXA_CAMINHO = 80
MIN_PIXELS_LINHA_PERTO = 300
DISTANCIA_MAX_ENTRE_FAIXAS = 120
VELOCIDADE_BASE_VETOR = 58
VELOCIDADE_MINIMA_VETOR = 30
VELOCIDADE_MAXIMA_VETOR = 90
KP_LATERAL = 0.25
KP_DIRECAO = 0.45
CORRECAO_MAXIMA_VETOR = 38
REDUZIR_VELOCIDADE_EM_CURVA = True
VELOCIDADE_BASE_CURVA_FORTE = 45
LIMIAR_DIRECAO_CURVA_FORTE = 45
ALPHA_SUAVIZACAO_ERRO = 0.65
TAMANHO_HISTORICO_ERRO = 8
TAMANHO_HISTORICO_DIRECAO = 8
MAX_FRAMES_LINHA_PERDIDA_BUSCA_SUAVE = 4
VELOCIDADE_BUSCA_SUAVE_BASE = 42
CORRECAO_BUSCA_SUAVE = 22
VELOCIDADE_BUSCA_GIRO = 45
TEMPO_MAX_BUSCA_GIRO = 1.2
FRAMES_REENCONTRO_LINHA = 2

# ===============================
# SPEC 07.1 - TRAVA DE PERDA E BUSCA
# ===============================
Y_TRAVA_BAIXA_INICIO = 0.72
Y_TRAVA_BAIXA_FIM = 0.98
MIN_PIXELS_LINHA_SEGURA_BAIXA = 250
MIN_PIXELS_LINHA_FRACA_BAIXA = 120
LIMIAR_ERRO_BAIXO_RISCO_PERDA = 115
FRAMES_CONFIRMAR_RISCO_PERDA = 2
FRAMES_CONFIRMAR_LINHA_PERDIDA = 1
VELOCIDADE_LINHA_FRACA = 42
KP_LINHA_FRACA = 0.18
CORRECAO_MAXIMA_LINHA_FRACA = 18
VELOCIDADE_BUSCA_TANQUE = 42
TEMPO_BUSCA_TANQUE_LADO = 0.45
TEMPO_MAX_BUSCA_TOTAL = 2.2
VELOCIDADE_VARREDURA = 38
TEMPO_VARREDURA_CURTA = 0.35
FRAMES_REENCONTRO_LINHA_BAIXA = 2
TEMPO_REALINHAR_APOS_BUSCA = 0.45
VELOCIDADE_REALINHAR_APOS_BUSCA = 40
KP_REALINHAR_APOS_BUSCA = 0.20
TAMANHO_HISTORICO_LADO = 10
LIMIAR_ERRO_LADO_CONFIAVEL = 20

# ===============================
# SPEC 07.2 - TANK ASSIST
# ===============================
LIMIAR_ERRO_BAIXO_RISCO_PERDA = 105
LIMIAR_DIRECAO_RISCO_PERDA = 65
FRAMES_CONFIRMAR_TANK_ASSIST = 2
KP_CURVA_FORTE = 0.42
CORRECAO_MAXIMA_CURVA_FORTE = 42
VELOCIDADE_MINIMA_CURVA_FORTE = 25
VELOCIDADE_MAXIMA_CURVA_FORTE = 90
VELOCIDADE_TANK_ASSIST = 42
TEMPO_PULSO_TANK_ASSIST = 0.12
TEMPO_MAX_TANK_ASSIST = 0.90
FRAMES_REENCONTRO_TANK_ASSIST = 2
LIMIAR_ERRO_SAIDA_TANK_ASSIST = 75
TEMPO_REALINHAR_APOS_TANK = 0.45
VELOCIDADE_REALINHAR_APOS_TANK = 42
KP_REALINHAR_APOS_TANK = 0.22
CORRECAO_MAXIMA_REALINHAR = 22

# ===============================
# SPEC 07.3 - RECUPERAR ANTES DE PARAR
# ===============================
PARAR_DEFINITIVO_AO_PERDER_LINHA = False
FRAMES_CONFIRMAR_LINHA_PERDIDA = 1
TEMPO_MAX_RECUPERACAO_LINHA = 2.5
TEMPO_PARAR_TEMPORARIO = 0.05
TEMPO_ESPERA_ARDUINO_RESET = 2.0
TENTATIVAS_CONFIRMAR_PARAR = 5
INTERVALO_TENTATIVA_PARAR = 0.25
TEMPO_MAX_BUSCA_TOTAL = 2.5

# ===============================
# RUN_STABLE - SEGUE-LINHA CONTINUO COM TANK ASSIST
# ===============================
INTERVALO_LOOP_RUN = 0.06
RUN_INTERVALO_LOOP = INTERVALO_LOOP_RUN
RUN_VELOCIDADE_BASE = 58
RUN_VELOCIDADE_MINIMA = 25
RUN_VELOCIDADE_MAXIMA = 90
RUN_KP_LATERAL = 0.24
RUN_KP_DIRECAO = 0.42
RUN_CORRECAO_MAXIMA = 38
RUN_VELOCIDADE_CURVA_FORTE = 45
RUN_KP_CURVA_FORTE_LATERAL = 0.30
RUN_KP_CURVA_FORTE_DIRECAO = 0.55
RUN_CORRECAO_MAXIMA_CURVA_FORTE = 45
RUN_LIMIAR_CURVA_FORTE = 55
RUN_Y_BAIXA_INICIO = 0.72
RUN_Y_BAIXA_FIM = 0.98
RUN_MIN_PIXELS_BAIXA_SEGURA = 230
RUN_MIN_PIXELS_BAIXA_FRACA = 100
RUN_LIMIAR_ERRO_BAIXA_RISCO = 95
RUN_FRAMES_RISCO_TANK = 1
RUN_CORRECAO_SATURADA_TANK = 35
RUN_FRAMES_CORRECAO_SATURADA = 2
RUN_VELOCIDADE_TANK = 44
RUN_TEMPO_PULSO_TANK = 0.10
RUN_TEMPO_MAX_TANK = 1.20
RUN_FRAMES_REENCONTRO_BAIXA = 2
RUN_LIMIAR_ERRO_SAIDA_TANK = 80
RUN_VELOCIDADE_BUSCA = 42
RUN_TEMPO_PULSO_BUSCA = 0.12
RUN_VELOCIDADE_VARREDURA = 38
RUN_TEMPO_PULSO_VARREDURA = 0.14
RUN_TEMPO_REALINHAR = 0.45
RUN_VELOCIDADE_REALINHAR = 42
RUN_KP_REALINHAR = 0.22
RUN_CORRECAO_MAXIMA_REALINHAR = 24
RUN_TAMANHO_HISTORICO_LADO = 16
RUN_LIMIAR_LADO_CONFIAVEL = 12
RUN_SALVAR_DEBUG_EVENTOS = True

# ===============================
# RUN_STABLE HOTFIX 1.1
# LADO CONFIAVEL + TANK IMEDIATO
# ===============================
RUN_LIMIAR_DIRECAO_LADO_CONFIAVEL = 45
RUN_LIMIAR_CORRECAO_LADO_CONFIAVEL = 25
RUN_LIMIAR_BAIXA_LADO_CONFIAVEL = 18
RUN_LIMIAR_DIRECAO_SAIDA_TANK = 55
RUN_LIMIAR_ERRO_SAIDA_TANK = 45
RUN_TANK_ASSIST_IMEDIATO = True

# ===============================
# RUN_STABLE 1.2 - DUAS BOLINHAS / LOOKAHEAD
# ===============================
RUN_NUM_FAIXAS_GUIA = 8
RUN_PONTO_ATUAL_Y_MIN = 0.72
RUN_PONTO_ATUAL_Y_MAX = 0.95
RUN_PONTO_ALVO_Y_MIN = 0.35
RUN_PONTO_ALVO_Y_MAX = 0.65
RUN_MIN_PIXELS_PONTO_GUIA = 80
RUN_DISTANCIA_MAX_CONEXAO_X = 140
RUN_DX_CURVA_FORTE = 55
RUN_DX_TANK_ASSIST = 85
RUN_ANGULO_TANK_ASSIST = 38
RUN_DX_SAIDA_TANK = 45
RUN_ANGULO_SAIDA_TANK = 22
RUN_KP_ATUAL = 0.22
RUN_KP_ALVO = 0.35
RUN_KP_DX = 0.30
RUN_VELOCIDADE_CURVA_FORTE = 44
RUN_KP_ATUAL_CURVA_FORTE = 0.18
RUN_KP_ALVO_CURVA_FORTE = 0.32
RUN_KP_DX_CURVA_FORTE = 0.45
RUN_CORRECAO_MAXIMA_CURVA_FORTE = 45
RUN_VELOCIDADE_TANK = 42
RUN_TEMPO_PULSO_TANK = 0.09
RUN_USAR_HISTORICO_APENAS_SE_LINHA_PERDIDA = True

# ===============================
# RUN_CLEAN - SEGUE-LINHA FINAL LIMPO
# ===============================

# Loop principal
RUN_CLEAN_INTERVALO = 0.06

# Divisao da ROI em faixas horizontais
RUN_CLEAN_NUM_FAIXAS = 12
RUN_CLEAN_MIN_PIXELS_FAIXA = 55

# Ponto atual: perto do robo
RUN_CLEAN_ATUAL_Y_MIN = 0.72
RUN_CLEAN_ATUAL_Y_MAX = 0.96

# Ponto alvo/lookahead: mais a frente
RUN_CLEAN_ALVO_Y_MIN = 0.25
RUN_CLEAN_ALVO_Y_MAX = 0.62

# Distancia maxima em X para conectar uma faixa com a proxima
RUN_CLEAN_MAX_SALTO_X = 150

# Controle normal
RUN_CLEAN_BASE_RETA = 58
RUN_CLEAN_BASE_CURVA = 46
RUN_CLEAN_BASE_EXTREMA = 34

# Limites de velocidade
RUN_CLEAN_VEL_MIN_NORMAL = 20
RUN_CLEAN_VEL_MIN_CURVA = 0

# Em curva extrema, permitir roda interna ir para tras
RUN_CLEAN_VEL_MIN_EXTREMA = -38
RUN_CLEAN_VEL_MAX = 90

# Ganhos do controle por ponto atual + alvo + dx
RUN_CLEAN_K_ATUAL = 0.22
RUN_CLEAN_K_ALVO = 0.28
RUN_CLEAN_K_DX = 0.40

# Ganhos para curva extrema
RUN_CLEAN_K_ATUAL_EXTREMA = 0.12
RUN_CLEAN_K_ALVO_EXTREMA = 0.22
RUN_CLEAN_K_DX_EXTREMA = 0.62

# Limites da correcao
RUN_CLEAN_CORRECAO_MAX_NORMAL = 38
RUN_CLEAN_CORRECAO_MAX_CURVA = 50
RUN_CLEAN_CORRECAO_MAX_EXTREMA = 70

# Classificacao de curva pelo dx e angulo
RUN_CLEAN_DX_CURVA = 45
RUN_CLEAN_DX_EXTREMA = 105
RUN_CLEAN_ANGULO_CURVA = 18
RUN_CLEAN_ANGULO_EXTREMA = 36

# Deteccao de cotovelo/90 real.
RUN_CLEAN_COTOVELO_DELTA_ANGULO = 42
RUN_CLEAN_COTOVELO_DX_MIN = 45
RUN_CLEAN_COTOVELO_MIN_PONTOS = 5

# Extrema por dx/angulo so se os dois forem fortes.
RUN_CLEAN_EXTREMA_DX_COM_ANGULO = 90
RUN_CLEAN_EXTREMA_ANGULO_COM_DX = 28

# Controle explicito de curva extrema.
RUN_CLEAN_EXTREMA_INTERNA_INICIAL = -10
RUN_CLEAN_EXTREMA_INTERNA_MAX_NEG = -38
RUN_CLEAN_EXTREMA_EXTERNA_INICIAL = 68
RUN_CLEAN_EXTREMA_EXTERNA_MAX = 90
RUN_CLEAN_EXTREMA_DX_FULL = 130
RUN_CLEAN_EXTREMA_ANGULO_FULL = 60

# Suavizacao temporal para nao ficar chacoalhando
RUN_CLEAN_ALPHA_SUAVIZACAO = 0.45

# Limitador de aceleracao entre comandos
RUN_CLEAN_DELTA_MAX_VELOCIDADE = 22
RUN_CLEAN_DELTA_MAX_EXTREMA = 45

# Recuperacao quando a linha sumir
RUN_CLEAN_VEL_RECUPERAR = 42
RUN_CLEAN_VEL_VARREDURA = 38
RUN_CLEAN_TEMPO_TROCA_VARREDURA = 0.35

# Historico do ultimo lado valido
RUN_CLEAN_HISTORICO_LADO = 10
RUN_CLEAN_DX_LADO_MIN = 25
RUN_CLEAN_ERRO_LADO_MIN = 18

# Debug
RUN_CLEAN_SALVAR_DEBUG_EVENTOS = True
RUN_CLEAN_INTERVALO_DEBUG = 0.50
