"""Configuracoes principais da Raspberry Pi."""

BAUD_RATE = 115200

# Use SERIAL_PORT = None para tentar detectar automaticamente.
# Se a deteccao falhar, definir manualmente, por exemplo:
# SERIAL_PORT = "/dev/ttyACM0"
SERIAL_PORT = None

VELOCIDADE_TESTE_BAIXA = 60
VELOCIDADE_TESTE_MEDIA = 80
VELOCIDADE_MAXIMA_SEGURA = 120
TIMEOUT_SERIAL = 2.0

MOTORES_ATIVADOS = True

CAMERA_HEIGHT_CM = 8
CAMERA_TILT_DEGREES = 35
CAMERA_FOV_DEGREES = 160

CAMERA_WIDTH = 640
CAMERA_HEIGHT = 480
CAMERA_FPS = 30
PASTA_CAPTURAS = "captures"

# ===============================
# CONFIGURACOES DA LINHA PRETA
# ===============================

# ROI em proporcao da imagem inteira.
ROI_Y_INICIO = 0.20
ROI_Y_FIM = 1.00
ROI_X_INICIO = 0.05
ROI_X_FIM = 0.95

# A parte superior esta mais distante da camera.
DIVISAO_TOPO_BAIXO = 0.40

# Preto em BGR: os tres canais da linha devem estar baixos.
PRETO_MIN_BGR = [0, 0, 0]
PRETO_MAX_TOPO_BGR = [90, 90, 90]
PRETO_MAX_BAIXO_BGR = [145, 145, 145]

# Area minima para aceitar um contorno como linha.
AREA_MINIMA_LINHA = 1500

# Limpeza simples da mascara.
KERNEL_LINHA = 3
ERODE_INICIAL = 2
DILATE_LINHA = 6
ERODE_FINAL = 2

# ===============================
# CONFIGURACOES DO COMANDO SUGERIDO
# ===============================

# Valores seguros para o primeiro teste real do robo.
# A ideia e comecar devagar e aumentar depois.
VELOCIDADE_BASE_SEGUE_LINHA = 60
VELOCIDADE_MINIMA_SEGUE_LINHA = 35
VELOCIDADE_MAXIMA_SEGUE_LINHA = 90

# Ganho proporcional inicial mais suave.
KP_SEGUE_LINHA = 0.30
CORRECAO_MAXIMA = 30

# Faixas proporcionais dentro da ROI.
FAIXA_BAIXA_INICIO = 0.65
FAIXA_BAIXA_FIM = 1.00
FAIXA_MEDIA_INICIO = 0.35
FAIXA_MEDIA_FIM = 0.65
FAIXA_ALTA_INICIO = 0.00
FAIXA_ALTA_FIM = 0.35

# A faixa baixa e a mais importante para a decisao.
PESO_FAIXA_BAIXA = 0.70
PESO_FAIXA_MEDIA = 0.25
PESO_FAIXA_ALTA = 0.05

# ===============================
# CONFIGURACOES DO PRIMEIRO SEGUE-LINHA REAL
# ===============================

DURACAO_TESTE_SEGUE_LINHA = 3.0
INTERVALO_COMANDO_SEGUNDOS = 0.10
PARAR_SE_PERDER_LINHA = True
MAX_FRAMES_SEM_LINHA = 2

# ===============================
# CONFIGURACOES DA SPEC 06
# RECUPERACAO DE LINHA E CURVA FECHADA
# ===============================

LIMIAR_ERRO_CURVA_FECHADA = 75
LIMIAR_ERRO_BAIXO_CURVA_FECHADA = 85
VELOCIDADE_BASE_NORMAL = 60
VELOCIDADE_BASE_CURVA_FECHADA = 50
KP_NORMAL = 0.30
KP_CURVA_FECHADA = 0.45
CORRECAO_MAXIMA_NORMAL = 30
CORRECAO_MAXIMA_CURVA_FECHADA = 45
VELOCIDADE_MAXIMA_CURVA_FECHADA = 95
VELOCIDADE_MINIMA_CURVA_FECHADA = 25
VELOCIDADE_GIRO_BUSCA = 50
TEMPO_MAX_BUSCA_LINHA = 1.2
MAX_FRAMES_SEM_LINHA_ANTES_BUSCA = 1
MAX_FRAMES_BUSCA_SEM_LINHA = 12
FRAMES_LINHA_REENCONTRADA = 2

# ===============================
# CONFIGURACOES DA SPEC 06.5
# CURVA 90 GRAUS COM PIVO CONTROLADO
# ===============================
LIMIAR_ERRO_CURVA_90 = 105
LIMIAR_ERRO_MEDIA_ALTA_CURVA_90 = 80
VELOCIDADE_GIRO_CURVA_90 = 55
TEMPO_MAX_CURVA_90 = 1.8
FRAMES_REENCONTRO_CURVA_90 = 2
LIMIAR_ERRO_SAIDA_CURVA_90 = 55
FRAMES_CONFIRMAR_CURVA_90 = 2
PAUSA_ANTES_GIRO_90 = 0.0

# ===============================
# SPEC 06.6 - CAMERA FRONTAL + ANTI-ZIGZAG
# ===============================
TEMPO_AVANCO_ANTES_GIRO_90 = 0.25
VELOCIDADE_AVANCO_ANTES_GIRO_90 = 45
TEMPO_MAX_GIRAR_90 = 2.0
TEMPO_MAX_TOTAL_CURVA_90 = 3.0
FRAMES_LINHA_BAIXA_REENCONTRADA_90 = 2
LIMIAR_ERRO_SAIDA_90 = 65
TEMPO_REALINHAR_POS_90 = 0.35
VELOCIDADE_BASE_REALINHAR_POS_90 = 45
KP_REALINHAR_POS_90 = 0.25
TAMANHO_HISTORICO_ERRO_ZIGZAG = 6
LIMIAR_ERRO_ZIGZAG = 35
MIN_TROCAS_SINAL_ZIGZAG = 2
TEMPO_MIN_ZIGZAG_SUAVE = 0.6
TEMPO_BLOQUEIO_CURVA_90_APOS_ZIGZAG = 1.0
VELOCIDADE_BASE_ZIGZAG = 50
KP_ZIGZAG = 0.18
CORRECAO_MAXIMA_ZIGZAG = 18
PESO_ZIGZAG_BAIXA = 0.85
PESO_ZIGZAG_MEDIA = 0.15
PESO_ZIGZAG_ALTA = 0.00

# ===============================
# SPEC 07 - VETOR E LOOKAHEAD
# ===============================
NUM_FAIXAS_CAMINHO = 9
Y_CONTROLE_PERTO_INICIO = 0.68
Y_CONTROLE_PERTO_FIM = 0.95
Y_LOOKAHEAD_INICIO = 0.35
Y_LOOKAHEAD_FIM = 0.68
Y_FUTURO_INICIO = 0.05
Y_FUTURO_FIM = 0.35
MIN_PIXELS_FAIXA_CAMINHO = 80
MIN_PIXELS_LINHA_PERTO = 300
DISTANCIA_MAX_ENTRE_FAIXAS = 120
VELOCIDADE_BASE_VETOR = 58
VELOCIDADE_MINIMA_VETOR = 30
VELOCIDADE_MAXIMA_VETOR = 90
KP_LATERAL = 0.25
KP_DIRECAO = 0.45
CORRECAO_MAXIMA_VETOR = 38
REDUZIR_VELOCIDADE_EM_CURVA = True
VELOCIDADE_BASE_CURVA_FORTE = 45
LIMIAR_DIRECAO_CURVA_FORTE = 45
ALPHA_SUAVIZACAO_ERRO = 0.65
TAMANHO_HISTORICO_ERRO = 8
TAMANHO_HISTORICO_DIRECAO = 8
MAX_FRAMES_LINHA_PERDIDA_BUSCA_SUAVE = 4
VELOCIDADE_BUSCA_SUAVE_BASE = 42
CORRECAO_BUSCA_SUAVE = 22
VELOCIDADE_BUSCA_GIRO = 45
TEMPO_MAX_BUSCA_GIRO = 1.2
FRAMES_REENCONTRO_LINHA = 2

# ===============================
# SPEC 07.1 - TRAVA DE PERDA E BUSCA
# ===============================
Y_TRAVA_BAIXA_INICIO = 0.72
Y_TRAVA_BAIXA_FIM = 0.98
MIN_PIXELS_LINHA_SEGURA_BAIXA = 250
MIN_PIXELS_LINHA_FRACA_BAIXA = 120
LIMIAR_ERRO_BAIXO_RISCO_PERDA = 115
FRAMES_CONFIRMAR_RISCO_PERDA = 2
FRAMES_CONFIRMAR_LINHA_PERDIDA = 1
VELOCIDADE_LINHA_FRACA = 42
KP_LINHA_FRACA = 0.18
CORRECAO_MAXIMA_LINHA_FRACA = 18
VELOCIDADE_BUSCA_TANQUE = 42
TEMPO_BUSCA_TANQUE_LADO = 0.45
TEMPO_MAX_BUSCA_TOTAL = 2.2
VELOCIDADE_VARREDURA = 38
TEMPO_VARREDURA_CURTA = 0.35
FRAMES_REENCONTRO_LINHA_BAIXA = 2
TEMPO_REALINHAR_APOS_BUSCA = 0.45
VELOCIDADE_REALINHAR_APOS_BUSCA = 40
KP_REALINHAR_APOS_BUSCA = 0.20
TAMANHO_HISTORICO_LADO = 10
LIMIAR_ERRO_LADO_CONFIAVEL = 20
